name: test-on-push

on: [push]

jobs:
  ci:
    name: Build, test, publish docs, and publish package
    runs-on: ubuntu-latest
    steps:
        - name: Check out source code
          uses: actions/checkout@v4

        - name: Enable Corepack
          run: corepack enable

        - name: Use Node.js ðŸ’»
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: yarn

        - name: Install dependencies
          run: yarn install --immutable

        - name: Build
          run: yarn build

        - name: Test
          run: yarn test

        - name: Build docs
          run: yarn docs

        - name: Copy build to docs/build
          run: |
            if [ -d "build" ]; then
              cp -r build docs/build
            fi

        - name: Copy examples to docs/examples
          run: |
            if [ -d "examples" ]; then
              cp -r examples docs/examples
            fi

        - name: Copy vendor files to docs/vendor
          run: |
            if [ -d "vendor" ]; then
              cp -r vendor docs/vendor
            fi

        - name: Deploy docs
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./docs # The folder the action should deploy.

        - name: Publish package
          run: yarn pkg-pr-new publish
